GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNTY5MTY2OTE1LCJleHAiOjE1NjkxNjY5MzB9.nGH7BzDjSbLxWE-axp2kWa_HGHAa4XKhIxw59-H5Gu8

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNTY5MTY3MjM3fQ.NrMhtoytSx5AGkn5GlNTfi6i11St-6NcxBC8ToaWPqk"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": 
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNTY5MTY3MjM3fQ.NrMhtoytSx5AGkn5GlNTfi6i11St-6NcxBC8ToaWPqk"}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Bob"
}